### ISSUE TITLE
The total number of paper for this year GECCO.

### ISSUE THREAD

**Issue by yuanjames** [ryojitanabe/ecconf#1]
Hi, I think the total number of paper for this year should be more than 386,  as my paper was marked as around 400.

**Comment by ryojitanabe** [comment]
Thanks for your comment. The number of submitted papers for GECCO2021 is based on an announcement to PC members. I guess that "the number of submitted papers" represents the number of *actually* submitted papers. The number of *abstract* submissions may be more than 400, but the number of *full-paper* submissions was actually 386. Of course, your comment may be correct. I will check an official announcement by GECCO2021.

**Comment by yuanjames** [comment]
> Thanks for your comment. The number of submitted papers for GECCO2021 is based on an announcement to PC members. I guess that "the number of submitted papers" represents the number of _actually_ submitted papers. The number of _abstract_ submissions may be more than 400, but the number of _full-paper_ submissions was actually 386. Of course, your comment may be correct. I will check an official announcement by GECCO2021.

Thanks for your nice summary of EA conferences.
