### ISSUE TITLE
Missing poster-only submissions for GECCO 2022

### ISSUE THREAD

**Issue by EKMeyerson** [ryojitanabe/ecconf#2]
Hello,

It looks like the calculation of poster acceptance for GECCO is missing the poster-paper submissions in the denominator. I think it should be:

(158 full acceptance + 210 full submissions accepted as posters + 32 poster-paper submissions accepted) / (426 full submission + 44 poster-paper submissions)

or

(210 full submissions accepted as posters + 32 poster-paper submissions accepted) / (426 full submission - 158 full acceptance + 44 poster-paper submissions)

Cheers,
---Elliot

**Comment by ryojitanabe** [comment]
Dear Elliot,

I am terribly sorry for the very late reply. I have not noticed this issue.

Thank you very much for your suggestion. I agree with your suggestion. We should take into account the number of poster-paper submissions to calculate the acceptance rate of poster papers accurately.

Unfortunately, GECCO does not announce the number of poster-paper submissions every year. For this reason, I use the incomplete calculation method to make the consistency. However, I may reconsider the method in the near future.
